const initial = {
  profile: {firstName:"Alex",lastName:"Morgan",email:"demo@profejoo.dev",location:"Berlin, Germany",headline:"Computer Engineering · ML & Systems",summary:"Research-oriented engineer building usable academic and data products."},
  resumes:[
    {id:1,title:"Research Internship CV",status:"Published",completeness:88,updated:"Sep 20, 2026"},
    {id:2,title:"Frontend Engineer CV",status:"Draft",completeness:74,updated:"Oct 1, 2026"}
  ],
  notifications:[
    {id:1,title:"Resume updated",body:"Your research-focused resume is ready for review.",read:false},
    {id:2,title:"New research matches",body:"Three professor profiles match your saved interests.",read:false},
    {id:3,title:"Profile tip",body:"Complete your links section to improve profile completeness.",read:true}
  ],
  messages:[{role:"bot",text:"Hi! This public demo uses deterministic local responses. Ask me about professors, CVs, or academic outreach."}]
};
const professors=[
  {name:"Dr. Sara Mitchell",uni:"Northbridge University",country:"Germany",field:"Machine Learning",h:47,citations:"12.6k",tags:["Deep Learning","NLP","Representation Learning"]},
  {name:"Dr. Daniel Cho",uni:"Westlake Institute of Technology",country:"Canada",field:"Computer Vision",h:39,citations:"8.9k",tags:["Robotics","Edge AI","Computer Vision"]},
  {name:"Dr. Leila Haddad",uni:"Riverton Technical University",country:"Netherlands",field:"Distributed Systems",h:35,citations:"7.2k",tags:["Cloud","Reliability","Distributed Systems"]},
  {name:"Dr. Kenji Watanabe",uni:"Eastport Science University",country:"Japan",field:"Human-Computer Interaction",h:31,citations:"5.4k",tags:["HCI","Accessibility","Interactive Systems"]}
];
const universities=[
  {name:"Northbridge University",country:"Germany",field:"Computer Science",rank:81},
  {name:"Westlake Institute of Technology",country:"Canada",field:"Engineering & Technology",rank:104},
  {name:"Riverton Technical University",country:"Netherlands",field:"Computer Science",rank:132},
  {name:"Eastport Science University",country:"Japan",field:"Information Systems",rank:149}
];
const navItems=[
  ["dashboard","▦","Dashboard"],["search","⌕","Search"],["profile","◉","Profile"],["resumes","▤","Resume Maker"],["notifications","●","Notifications"],["chat","✦","Chatbot"],["about","i","Frontend Scope"]
];
const load=(k,f)=>{try{return JSON.parse(localStorage.getItem("pf-demo-"+k))||f}catch{return f}};
let state={profile:load("profile",initial.profile),resumes:load("resumes",initial.resumes),notifications:load("notifications",initial.notifications),messages:load("messages",initial.messages)};
let current="dashboard";
const save=(k)=>localStorage.setItem("pf-demo-"+k,JSON.stringify(state[k]));
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const nav=document.getElementById("nav"),view=document.getElementById("view"),title=document.getElementById("page-title");
function renderNav(){nav.innerHTML=navItems.map(([id,icon,label])=>`<button class="nav-btn ${id===current?"active":""}" data-nav="${id}"><span class="nav-icon">${icon}</span><span class="nav-label">${label}</span></button>`).join("");nav.querySelectorAll("[data-nav]").forEach(b=>b.onclick=()=>{current=b.dataset.nav;render()})}
function render(){renderNav();const labels=Object.fromEntries(navItems.map(([id,,l])=>[id,l]));title.textContent=labels[current];view.innerHTML=({dashboard:dashboardView,search:searchView,profile:profileView,resumes:resumesView,notifications:notificationsView,chat:chatView,about:aboutView}[current])();bind()}
function dashboardView(){const unread=state.notifications.filter(n=>!n.read).length;return `<div class="notice">This public version intentionally replaces private backend, production datasets, AI services, and secrets with browser-local mocks.</div><div class="grid cards"><div class="card"><div class="label">Profile completeness</div><div class="metric">88%</div><div class="muted">12 sections handled</div></div><div class="card"><div class="label">Saved resumes</div><div class="metric">${state.resumes.length}</div><div class="muted">CRUD + autosave-oriented flow</div></div><div class="card"><div class="label">Research matches</div><div class="metric">${professors.length}</div><div class="muted">Professor / university search demo</div></div><div class="card"><div class="label">Unread alerts</div><div class="metric">${unread}</div><div class="muted">Notification read state</div></div></div><div class="section-head"><h2>Frontend flows included</h2></div><div class="two-col"><div class="feature-list"><div class="feature"><strong>Search & filtering</strong><span class="muted">Mode switching, filters, sort-ready response shapes and professor cards.</span></div><div class="feature"><strong>Structured profile</strong><span class="muted">Basics, education, experience, outputs, credentials, skills, links and more.</span></div><div class="feature"><strong>Resume workspace</strong><span class="muted">List/card patterns, create, edit, duplicate, delete, template and export-oriented UI.</span></div></div><div class="feature-list"><div class="feature"><strong>Authentication UX</strong><span class="muted">Login, signup, OTP, forgot/reset password and protected routes in the React source.</span></div><div class="feature"><strong>Notifications</strong><span class="muted">Unread/read grouping, detail routing and mark-as-read handling.</span></div><div class="feature"><strong>Chat / FAQ</strong><span class="muted">Guest/session service layer replaced with deterministic demo responses.</span></div></div></div>`}
function searchView(){return `<div class="card"><div class="filters"><input id="q" class="input" placeholder="Search professor, university or field…"><select id="country"><option value="">All countries</option>${[...new Set(professors.map(p=>p.country))].map(x=>`<option>${x}</option>`).join("")}</select><select id="mode"><option>Professor</option><option>University</option></select><button class="primary" id="run-search">Search</button></div></div><div class="section-head"><h2 id="result-title">Professor results</h2><span class="muted" id="result-count">${professors.length} matches</span></div><div id="results" class="prof-grid">${profCards(professors)}</div>`}
function profCards(rows){return rows.map(p=>`<article class="card prof"><div class="prof-avatar">${p.name.split(" ").filter(x=>!x.includes("Dr.")).map(x=>x[0]).slice(0,2).join("")}</div><div><h3>${esc(p.name)}</h3><div class="muted">${esc(p.uni)} · ${esc(p.country)}</div><div class="row-actions" style="margin-top:8px"><span class="badge">H-index ${p.h}</span><span class="badge green">${p.citations} citations</span></div><div class="tags">${p.tags.map(t=>`<span class="tag">${esc(t)}</span>`).join("")}</div></div></article>`).join("")||`<div class="card empty">No matching professors in the demo dataset.</div>`}
function universityCards(rows){return rows.map(u=>`<article class="card"><div class="label">QS demo rank #${u.rank}</div><h3 style="color:var(--navy);margin-bottom:6px">${esc(u.name)}</h3><div class="muted">${esc(u.country)} · ${esc(u.field)}</div></article>`).join("")||`<div class="card empty">No matching universities in the demo dataset.</div>`}
function profileView(){const p=state.profile;return `<div class="profile-layout"><div class="card"><div class="section-head" style="margin-top:0"><h2>Edit profile basics</h2><span class="badge green">Saved locally</span></div><form id="profile-form" class="form-grid"><div class="field"><label>First name</label><input class="input" name="firstName" value="${esc(p.firstName)}"></div><div class="field"><label>Last name</label><input class="input" name="lastName" value="${esc(p.lastName)}"></div><div class="field"><label>Email</label><input class="input" name="email" value="${esc(p.email)}"></div><div class="field"><label>Location</label><input class="input" name="location" value="${esc(p.location)}"></div><div class="field full"><label>Headline</label><input class="input" name="headline" value="${esc(p.headline)}"></div><div class="field full"><label>Summary</label><textarea rows="5" name="summary">${esc(p.summary)}</textarea></div><div class="field full"><button class="primary">Save profile</button></div></form></div><div class="resume-preview"><div class="label">Live preview</div><h2>${esc(p.firstName)} ${esc(p.lastName)}</h2><div class="muted">${esc(p.headline)}</div><p>${esc(p.summary)}</p><h3>Profile sections</h3><div class="tags">${["Education","Experience","Publications","Projects","Talks","Honors","Credentials","Skills","Links","Languages","Interests","Extras"].map(x=>`<span class="tag">${x}</span>`).join("")}</div></div></div>`}
function resumesView(){return `<div class="section-head" style="margin-top:0"><div><h2>Resume workspace</h2><div class="muted">Local mock CRUD for portfolio demonstration</div></div><button class="primary" id="new-resume">+ New resume</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Title</th><th>Status</th><th>Completeness</th><th>Updated</th><th>Actions</th></tr></thead><tbody>${state.resumes.map(r=>`<tr><td><strong>${esc(r.title)}</strong></td><td><span class="badge ${r.status==="Published"?"green":""}">${r.status}</span></td><td>${r.completeness}%</td><td>${r.updated}</td><td><div class="row-actions"><button class="secondary" data-dup="${r.id}">Duplicate</button><button class="danger" data-del="${r.id}">Delete</button></div></td></tr>`).join("")}</tbody></table>${state.resumes.length?"":`<div class="empty">No resumes yet.</div>`}</div>`}
function notificationsView(){return `<div class="grid">${state.notifications.map(n=>`<article class="card notification ${!n.read?"unread":""}"><div><div class="label">${n.read?"Read":"Unread"}</div><h3 style="margin:4px 0;color:var(--navy)">${esc(n.title)}</h3><div class="muted">${esc(n.body)}</div></div>${!n.read?`<button class="secondary" data-read="${n.id}">Mark read</button>`:`<span class="badge green">Done</span>`}</article>`).join("")}</div>`}
function chatView(){return `<div class="chat-shell"><div class="card chat-box"><div class="messages" id="messages">${state.messages.map(m=>`<div class="msg ${m.role==="user"?"user":"bot"}">${esc(m.text)}</div>`).join("")}</div><form class="composer" id="chat-form"><input class="input" name="message" autocomplete="off" placeholder="Ask about CVs, professors or outreach…"><button class="primary">Send</button></form></div><div class="card"><div class="label">Try these</div><div class="quick-list" style="margin-top:12px"><button class="ghost" data-ask="How should I shortlist professors?">Shortlist professors</button><button class="ghost" data-ask="How can I improve my CV?">Improve my CV</button><button class="ghost" data-ask="How should I email a professor?">Academic outreach</button></div><div class="notice" style="margin-top:18px">No message is sent to an external AI service in this public demo.</div></div></div>`}
function aboutView(){return `<div class="card"><div class="label">Portfolio disclosure</div><h2 style="color:var(--navy)">Team project, public-safe reconstruction</h2><p class="muted">The original product was developed by a 6-person team. The portfolio owner reports implementing roughly 80% of the frontend. This public repository is intentionally reconstructed and sanitized: private backend code, production data, secrets, internal infrastructure and real AI/search services are not published.</p></div><div class="section-head"><h2>Frontend engineering represented in the source</h2></div><div class="two-col"><div class="feature-list"><div class="feature"><strong>React 19 + TypeScript + Vite</strong><span class="muted">Routing, contexts, service modules and reusable component architecture.</span></div><div class="feature"><strong>Radix UI + Tailwind CSS</strong><span class="muted">Accessible primitives, dialogs, sheets, tabs, selects and responsive layouts.</span></div><div class="feature"><strong>Forms & validation</strong><span class="muted">React Hook Form + Zod patterns across authentication and structured profile editing.</span></div><div class="feature"><strong>Rich editor</strong><span class="muted">Tiptap-based Email/SOP editing flows with local draft persistence.</span></div></div><div class="feature-list"><div class="feature"><strong>API integration layer</strong><span class="muted">Axios instances, JWT/refresh handling, adapters and error normalization.</span></div><div class="feature"><strong>Resume builder</strong><span class="muted">Structured section mapping, live editing, autosave-oriented flow, print/export and LaTeX generation.</span></div><div class="feature"><strong>Search UX</strong><span class="muted">Professor/university modes, filter metadata, pagination and sort handling.</span></div><div class="feature"><strong>Stateful UI</strong><span class="muted">Protected routes, context providers, local persistence, empty/loading/error states and notifications.</span></div></div></div>`}
function reply(q){const x=q.toLowerCase();if(x.includes("professor")||x.includes("shortlist"))return "Prioritize research-fit first, then check recent publications, lab activity, supervision history, and whether the professor is actively accepting students.";if(x.includes("cv")||x.includes("resume"))return "Keep it targeted and scannable: lead with relevant projects/research, quantify outcomes, reduce generic bullets, and tailor keywords to the role or lab.";if(x.includes("email")||x.includes("outreach"))return "Use a short subject, one specific connection to the professor’s work, one or two relevant experiences, and a clear ask. Avoid generic mass-email language.";return "This is a deterministic demo reply. Try asking about professors, CVs, or academic outreach."}
function bind(){if(current==="search"){document.getElementById("run-search").onclick=()=>{const q=document.getElementById("q").value.toLowerCase(),country=document.getElementById("country").value,mode=document.getElementById("mode").value;let rows=mode==="Professor"?professors:universities;rows=rows.filter(r=>(!q||JSON.stringify(r).toLowerCase().includes(q))&&(!country||r.country===country));document.getElementById("result-title").textContent=mode+" results";document.getElementById("result-count").textContent=rows.length+" matches";document.getElementById("results").innerHTML=mode==="Professor"?profCards(rows):universityCards(rows)}}if(current==="profile"){document.getElementById("profile-form").onsubmit=e=>{e.preventDefault();const d=new FormData(e.target);state.profile=Object.fromEntries(d.entries());save("profile");render()}}if(current==="resumes"){document.getElementById("new-resume").onclick=()=>{const id=Date.now();state.resumes.unshift({id,title:"New Portfolio Resume",status:"Draft",completeness:42,updated:"Just now"});save("resumes");render()};view.querySelectorAll("[data-dup]").forEach(b=>b.onclick=()=>{const r=state.resumes.find(x=>x.id==b.dataset.dup);state.resumes.unshift({...r,id:Date.now(),title:r.title+" (Copy)",status:"Draft",updated:"Just now"});save("resumes");render()});view.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>{state.resumes=state.resumes.filter(x=>x.id!=b.dataset.del);save("resumes");render()})}if(current==="notifications"){view.querySelectorAll("[data-read]").forEach(b=>b.onclick=()=>{state.notifications=state.notifications.map(n=>n.id==b.dataset.read?{...n,read:true}:n);save("notifications");render()})}if(current==="chat"){const send=q=>{if(!q.trim())return;state.messages.push({role:"user",text:q.trim()},{role:"bot",text:reply(q)});save("messages");render()};document.getElementById("chat-form").onsubmit=e=>{e.preventDefault();send(new FormData(e.target).get("message")||"")};view.querySelectorAll("[data-ask]").forEach(b=>b.onclick=()=>send(b.dataset.ask));const box=document.getElementById("messages");box.scrollTop=box.scrollHeight}}
document.getElementById("reset-demo").onclick=()=>{Object.keys(localStorage).filter(k=>k.startsWith("pf-demo-")).forEach(k=>localStorage.removeItem(k));state=JSON.parse(JSON.stringify(initial));render()};render();
